name: Start downstream tests

on:
  push:
    branches:
      - main
      - develop
      - releases/**
    paths:
      - '**.py'
      - '**.yml'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - '**.py'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [ 'VOLTTRON/volttron-openadr-ven', 'VOLTTRON/volttron-listener-agent' ]
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.ACTION_HOOK_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: downstream-testing
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'


